// <auto-generated />
namespace Projeto_NFe.Infra.ORM.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class NFeContext_V4 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(NFeContext_V4));
        
        string IMigrationMetadata.Id
        {
            get { return "201810101959197_NFeContext_V4"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
