// <auto-generated />
namespace Projeto_NFe.Infra.ORM.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class NFeContext_V23 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(NFeContext_V23));
        
        string IMigrationMetadata.Id
        {
            get { return "201810092132500_NFeContext_V2.3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
