CREATE TABLE [dbo].[TBNotaFiscalEmitida] (
    [Id_NotaFiscalEmitida]               INT             IDENTITY (1, 1) NOT NULL,
    [NaturezaOperacao]                   VARCHAR (40)    NOT NULL,
    [DataEmissao]                        DATETIME        NOT NULL,
    [DataEntrada]                        DATETIME        NOT NULL,
    [ChaveAcesso]                        VARCHAR (40)    NOT NULL,
    [EmitenteNomeFantasia]               VARCHAR (40)    NOT NULL,
    [EmitenteRazaoSocial]                VARCHAR (40)    NOT NULL,
    [EmitenteCnpj]                       VARCHAR (40)    NOT NULL,
    [EmitenteInscricaoEstadual]          VARCHAR (40)    NOT NULL,
    [EmitenteInscricaoMunicipal]         VARCHAR (40)    NOT NULL,
    [EmitenteLogradouro]                 VARCHAR (40)    NOT NULL,
    [EmitenteNumero]                     INT             NOT NULL,
	[EmitenteBairro] VARCHAR(40) NOT NULL, 
    [EmitenteMunicipio]                  VARCHAR (40)    NOT NULL,
    [EmitenteEstado]                     VARCHAR (40)    NOT NULL,
    [EmitentePais]                       VARCHAR (40)    NOT NULL,
    [ImpostoNotaFiscalValorIpiNota]      DECIMAL (18, 2) NOT NULL,
    [ImpostoNotaFiscalValorIcmsNota]     DECIMAL (18, 2) NOT NULL,
    [ImpostoNotaFiscalValorFrete]        DECIMAL (18, 2) NOT NULL,
    [ImpostoNotaFiscalValorTotalProduto] DECIMAL (18, 2) NOT NULL,
    [ImpostoNotaFiscalValorTotalNota]    DECIMAL (18, 2) NOT NULL,
    [DestinatarioNome]                   VARCHAR (40)    NULL,
    [DestinatarioRazaoSocial]            VARCHAR (40)    NULL,
    [DestinatarioCnpj]                   VARCHAR (40)    NULL,
    [DestinatarioCpf]                    VARCHAR (40)    NULL,
    [DestinatarioInscricaoEstadual]      VARCHAR (40)    NULL,
    [DestinatarioLogradouro]             VARCHAR (40)    NOT NULL,
    [DestinatarioNumero]                 INT             NOT NULL,
    [DestinatarioBairro]                 VARCHAR (40)    NOT NULL,
    [DestinatarioMunicipio]              VARCHAR (40)    NOT NULL,
    [DestinatarioEstado]                 VARCHAR (40)    NOT NULL,
    [DestinatarioPais]                   VARCHAR (40)    NOT NULL,
    [TransportadorNomeFantasia]          VARCHAR (40)    NULL,
    [TransportadorRazaoSocial]           VARCHAR (40)    NULL,
    [TransportadorCnpj]                  VARCHAR (40)    NULL,
    [TransportadorCpf]                   VARCHAR (40)    NULL,
    [TransportadorInscricaoEstadual]     VARCHAR (40)    NULL,
    [TransportadorResponsabilidadeFrete] VARCHAR (40)    NOT NULL,
    [TransportadorLogradouro]            VARCHAR (40)    NOT NULL,
    [TransportadorNumero]                INT             NOT NULL,
    [TransportadorBairro]                VARCHAR (40)    NOT NULL,
    [TransportadorMunicipio]             VARCHAR (40)    NOT NULL,
    [TransportadorEstado]                VARCHAR (40)    NOT NULL,
    [TransportadorPais]                  VARCHAR (40)    NOT NULL
    PRIMARY KEY CLUSTERED ([Id_NotaFiscalEmitida] ASC)
);

